- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - copy:
      src: ./conf/nginx/default
      dest: /etc/nginx/sites-available/default

  - name: Restart nginx
    service: name=nginx state=restarted


    