- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    app_jar: DAW-videoclub-1.0-SNAPSHOT.jar
    app_src_path: ../target
    app_dest_path: /home/vagrant

  tasks:
  - copy:
      src: "{{ app_src_path }}/{{ app_jar }}"
      dest: "{{ app_dest_path }}"

  - apt_repository:
      repo: ppa:webupd8team/java
      state: present

  - name: apt-get update
    apt:
      update_cache: yes

  - name: Installing java8
    shell: |
      echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
      echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
      sudo apt-get -y install oracle-java8-installer
      
  - name: Runing app!!!
    command: "java -jar {{ app_dest_path }}/{{ app_jar }} 2>&1 "


