
BOX_IMAGE = "atorre/daw"
NODE_COUNT = 1

Vagrant.configure(2) do |config|
	
	#Load balancer
	config.vm.define "loadbalancer" do |load_balancer|
		load_balancer.vm.box = BOX_IMAGE
		load_balancer.vm.hostname = "loadbalancer"
		#load_balancer.vm.network "forwarded_port", guest: 80, host: 8080
		load_balancer.vm.network :private_network, ip: "10.0.0.10"

		load_balancer.vm.provision :ansible do |ansible|
			ansible.playbook = "load_balancer.yml"
		end
	end

	#DB server
	config.vm.define "database" do |data_base|
		data_base.vm.box = BOX_IMAGE
		data_base.vm.hostname = "database"
		data_base.vm.network :private_network, ip: "10.10.10.10"

		data_base.vm.provision :ansible do |ansible|
			ansible.playbook = "mysql.yml"
		end
	end
	 
	#Slaves
	(1..NODE_COUNT).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.box = BOX_IMAGE
			node.vm.hostname = "node#{i}"
			node.vm.network :private_network, ip: "10.0.0.#{i + 10}"

			node.vm.provision :ansible do |ansible|
				ansible.playbook = "node.yml"
			end
		end
	end

end